server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  # hostname: localhost # eureka服务端的实例名称
  client:
    register-with-eureka: false # false表明不注册自己
    fetch-registry: false # false即自己是注册中心，职责是维护服务实例，并不需要去检索服务
    service-url:
      # 设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
#      defaultZone: http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000